apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-pi-hole-data
  namespace: pi-hole
  labels:
    volume: pi-hole-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/etc/pihole/server1"