apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pi-hole-dnsmasq-pvc
  namespace: pi-hole
spec:
  selector:
    matchLabels:
      volume: pi-hole-dnsmasq
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi