apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: webapp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-203
    metallb.universe.tf/loadBalancerIPs: 192.168.178.203
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  selector:
    app: webapp

---
apiVersion: v1
kind: Service
metadata:
  namespace: pi-hole
  name: dns-server
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-203
    metallb.universe.tf/loadBalancerIPs: 192.168.178.203
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.203
  sessionAffinity: ClientIP
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
    - name: dns-dhcp
      protocol: UDP
      port: 67
      targetPort: dns-dhcp
  selector:
    app: webapp

